// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxbrulnpiszscjbipeiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4YnJ1bG5waXN6c2NqYmlwZWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTYzMzgsImV4cCI6MjA3NDA5MjMzOH0.iTck7UmO1z07sU5Xj-3HQPIBc_aSZS-dGY7GhSakwec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});